### ISSUE TITLE
new, improved, port of qed, and more info on the Caltech sources

### ISSUE THREAD

**Issue by phonologus** [arnoldrobbins/qed-archive#2]
I've recently been through a spate of _Qed_ development, which has resulted in a brand new, and much better, port of _Qed_, (with UTF-8 support) than the one you link to in your README. Could you update your README to point to my new port [here][Q]. I have also done a lot of work on updating Rob's original _Qed Tutorial_, and making it pretty. Repo is [here][R]. And could you correct the spelling of my surname: I'm _Jensen_ (not _Jesen_)?

[Q]: https://github.com/phonologus/qed-new
[R]: https://github.com/phonologus/qed-book

Separately, your `usenix-80-caltech` repo misses the including directory, which has a full set of the then current _Qed_ sourcecode. It's not obvious, because it's not in a named sub-directory, but a `cd ..` in the Unix Archive from the directory you have mirrored in `usenix-80-caltech` contains the then current sources for _Qed_!

**Comment by learning-vi** [comment]
@phonologus Thanks for the info.  I don't have much time at the moment for this repo; would you be kind enough to prepare a pull request that fixes the problems? If you wish to prepare two PRs for the two issues, that's fine too.

Thank you very much!

**Comment by arnoldrobbins** [comment]
@phonologus I wrote the previous comment; I was logged in on a different account and didn't realize it. Thanks.

**Comment by phonologus** [comment]
Thank you for the merge of the README updates. I'm preparing a pull-request for the Caltech sources. It's a fascinating tarball as it contains not only `qed`, but the customised UofT `ed`, and a lot of documentation (including a version of Rob's Qed tutorial). I am sanitizing it slightly by removing the binary object code, and preparing a README file that catalogues what's what.

**Comment by arnoldrobbins** [comment]
This is awesome. Thanks for handling this, I appreciate it.

**Comment by arnoldrobbins** [comment]
@phonologus I have merged your second PR. There was one PDP-11 binary left, which I removed, and I made some minor updates to two of the README.md files.

If you're on the TUHS list, feel free to announce the updates, as well as your new version of Qed, there. If not, I will do so.

Thanks again for your contributions! I appreciate the help.

**Comment by phonologus** [comment]
Thank you Arnold for taking the time to merge these changes. I'm not on the TUHS (I keep a low online profile...), so if you are happy to point interested parties to the updates, please do.

Happy to be able to contribute. It is a privilege.
